### PR TITLE
Attempt to de-flake shared_detached_filters.rb

### PR DESCRIPTION
**Pull request by JasonBarnabe**
And fix a spelling mistake. And I think we only need to be told once about utf-8.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Failed on an unrelated test, filed #44.

**Comment by JasonBarnabe** [comment]
Failed on the test from #43.

**Comment by JasonBarnabe** [comment]
@patricklindsay I'm not as sure that this will fix the issue as I could never get this to happen locally. You may want to try to trigger CircleCI a few more times on this to see if it happens again.

**Comment by patricklindsay** [comment]
Whoops merged instead - fingers crossed!

**Pull request merged**
